# Site
repository: cowienduckie/resume-cowienduckie.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minh Tran
title: Web Developer
email: minhtran.2404@outlook.com
phone: (+84)96 221 5871
website: lowkeycode.me

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username: cowienduckie
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: cowienduckie
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: minhtran2404
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Download English Resume
    icon: fas fa-arrow-down
    url: resume.lowkeycode.me/files/MinhTran_Resume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Minh Tran, a web developer. I have a year of experience in .NET core Development and good knowledge of SQL Server, Database Design, and Object-oriented Programming.

  Learning new things is my strength. I currently strive to learn ReactJS and sharpen my .NET Development skills. 

  My the most favorite technical books are <mark>Algorithm (Jeff Erickson)</mark>.

  Technical skills
    -	Programming Languages: <mark>C#</mark> <mark>JavaScript</mark> <mark>HTML/CSS</mark> <mark>C/C++</mark>
    -	Frameworks/ Platforms:
      -	<mark>.NET Core</mark> <mark>ASP .NET MVC</mark> <mark>ASP .NET Web API</mark> <mark>Entity Framework</mark>
      -	<mark>ReactJs</mark>
    - Database Management System: <mark>MS SQL Server</mark> <mark>PostgreSQL</mark>
    - Tools: <mark>Git</mark>, <mark>Github workflow</mark>, <mark>Azure Web Service</mark>

content:
  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NashTech
        link: https://nashtechglobal.com/
        link_text: nashtechglobal.com
        sub_title: Software Engineer
        caption: January 2023 - Present

      - layout: left
        title: NashTech
        link: https://nashtechglobal.com/
        link_text: nashtechglobal.com
        sub_title: Software Engineer Intern
        caption: September 2022 - December 2022
        description: | # this will include new lines to allow paragraphs
          Deliver a mock project by collaborating with a team of ten members (including Developers and Testers) and one Project Manager as a dev team leader in two Scrum sprints.

          Complete two-month training about .NET Development, ReactJS, Git, Agile Scrum, English, and soft skills.

          Achieve an acknowledgment of completion with an Excellent grade from NashTech.

          Technology stack: <mark>.NET 6</mark> <mark>ASP .NET Web API</mark> <mark>SQL Server</mark> <mark>ReactJS</mark> <mark>Git</mark>

      - layout: left
        title: Viettel IDC
        link: https://www.viettelidc.com.vn
        link_text: viettelidc.com.vn
        sub_title: Web Development Intern
        caption: August 2021 - April 2022
        description: | # this will include new lines to allow paragraphs
          Release two new cloud services by collaborating with dev teams in full Scrum sprints and Development life cycle, including service's workflow design, implementation, testing, and debugging.

          Conduct precision assessment of services' workflow and database data as well as fix bugs.

          Complete three-month training about .NET Development, SQL Server, system architecture, and database design.

          Technology stack: <mark>.NET Framework</mark> <mark>ASP .NET MVC</mark> <mark>SQL Server</mark> <mark>KnockoutJS</mark> <mark>Git</mark>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hanoi University of Science and Technology (HUST)
        caption: September 2018 - 2023
        description: | # this will include new lines to allow paragraphs
          Bachelor of Engineering in Computer Engineering - GPA 2.6/4.0.

          Coursework: Algorithms & Data Structures, Object Oriented Design & Programming, Database Systems, Networks & Communications, Web Technologies & e-Services.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Web Application for Online Asset Management System
        caption: November 2022 - December 2022
        link: https://github.com/cowienduckie/TheRookiesFinal
        link_text: Project Website
        additional_links:
          - title: Github repository
            icon: fab fa-github fa-2x
            url: https://github.com/cowienduckie/TheRookiesFinal
        description: | # this will include new lines to allow paragraphs
          Build an web application for the online asset management system, and deploy it on Azure Web Service. This application provides CRUD features for admin to manage asset, assignment and returning request.

          Technology stack: <mark>.NET 6</mark> <mark>ASP .NET Web API</mark> <mark>Entity Framework</mark> <mark>SQL Server</mark> <mark>ReactJS</mark> <mark>Ant Design</mark>

      - layout: left
        border: weak
        title: E-Commerce Web Application for Clothing Shop
        caption: November 2021 - January 2022
        link: https://lowkeycode.me/.net/2022/01/23/clothing-shop-v1.html
        link_text: Project Website
        additional_links:
          - title: Github repository
            icon: fab fa-github fa-2x
            url: https://github.com/cowienduckie/ClothingShop
          - title: Live Demo
            icon: fas fa-globe fa-2x
            url: https://clothingshop.azurewebsites.net/
        description: | # this will include new lines to allow paragraphs
          Build an E-commerce web application for the client's business clothing shop, and deploy it on <mark>Azure</mark>. This application provides User features, such as product SKUs with sizes and colors, shopping cart, COD payment, membership vouchers, etc., and Admin features.

          Technology stack: <mark>.NET Core 3.1</mark> <mark>ASP .NET MVC</mark> <mark>Entity Framework</mark> <mark>SQL Server</mark> <mark>Bootstrap</mark>

footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml"
  ]
