# Site
repository: cowienduckie/resume-cowienduckie.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minh Tran
title: Web Developer
email: minhtran.2404@outlook.com
phone: (+84)96 221 5871
website: lowkeycode.me

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  cowienduckie
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: cowienduckie
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: minhtran2404
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Minh Tran, a “lowkey” web developer. I have over one year of experience in <mark>.NET Core Development</mark> and good knowledge of <mark>SQL Server</mark>, <mark>Database Design</mark>, and <mark>Object-oriented Programming</mark>.
  Learning and absorbing new knowledge is my strength and leisure pursuit. Currently, I am striving to learn <mark>ReactJS</mark> and sharpen my <mark>.NET Development</mark> skills. Besides, colleagues and friends deem me a good team player because I always match up with people I haven’t worked with before and adapt to an entirely new team. Thus, I believe such a situation offers an excellent way to improve my communication skills as well as acquire more insightful perspectives from various standpoints. 
  My favorite technical book is <mark>Algorithm (Jeff Erickson)</mark>.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: E-Commerce Web Application for Clothing Shop
        link: github.com/cowienduckie/ClothingShop
        link_text: Github Repository
        link: https://lowkeycode.me/.net/2022/01/23/clothing-shop-v1.html
        link_text: Project Website
        additional_links:
          - title:  Github repository
            icon: fab fa-github fa-2x
            url: https://github.com/cowienduckie/ClothingShop          
          - title: Live Demo
            icon: fa-solid fa-globe fa-2x
            url: https://clothingshop.azurewebsites.net/
        quote: >
          This web app is a school project I partook in as the Team Leader in a subject named “Introduction to Software Development”.
        description: | # this will include new lines to allow paragraphs
          In this project, I was the leader of an <mark>Agile team</mark> with seven members, working together to build a web application for a client’s business clothing shop. Among a wide range of technologies, we decided to use <mark>ASP .NET core MVC</mark> with <mark>SQL Server</mark> for the back-end and <mark>Bootstrap</mark> as a visually appealing and easy-to-use UI framework for the front-end.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Viettel IDC
        link: viettelidc.com.vn 
        # link_text: boringcompany.com
        sub_title: Software Development Intern
        caption: August 2021 - April 2022        
        description: | # this will include new lines to allow paragraphs
          An internship at Viettel IDC - the leading data center and cloud computing services provider in Vietnam, definitely was a good and valuable experience for me. In my nine months working there, I have attained excellent skillsets in solving technical problems and administering teamwork.
          After three months of training in <mark>.NET Development</mark>, I was allowed to join an actual project building the Viettel IDC’s official website. My training involves <mark>system architecture</mark>, <mark>database design</mark>, and all <mark>primary services majors</mark> for the following six months. In addition, I joined the dev team to release the company’s <mark>two newest services</mark> while maintaining currently available ones.  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hanoi University of Science and Technology (HUST)
        caption: September 2018 - 2023
        sub_title: BE Computer Engineering
        description: | # this will include new lines to allow paragraphs
          During my time at HUST, I have learned a considerable amount of technical knowledge, such as <mark>solving complicated problems</mark>, <mark>managing an IT project</mark>, <mark>building an application</mark> in the modern world, and furthermore. 
          Moreover, I enjoy subjects related to <mark>algorithms</mark> because I like to solve problems and induce logical thinking to reach the final answers. 
          Also, the competitive environment at HUST has reinforced my ability to work under tight deadlines and extreme pressure.
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]